# file name
# FILE_PATH = "../ai/resource/data.xlsx"
FILE_PATH = "../ai/resource/data.xlsx"
# machine name
MACHINE_NAME = "../ai/resource/machine.pickle"

# sheet index
SHEET_PRODUCT = 0
SHEET_VIDEO = 1
SHEET_SALON = 2
SHEET_STUDY = 3
SHEET_PRODUCT_HELPER = 4
SHEET_VIDEO_HELPER = 5
SHEET_SALON_HELPER = 6
SHEET_STUDY_HELPER = 7


# feature - texture
TEXTURE_TYPE_1A_1B = "1A/1B"
TEXTURE_TYPE_1C = "1C"
TEXTURE_TYPE_2A = "2A"
TEXTURE_TYPE_2B = "2B"
TEXTURE_TYPE_2C = "2C"
TEXTURE_TYPE_3A = "3A"
TEXTURE_TYPE_3B = "3B"
TEXTURE_TYPE_3C = "3C"
TEXTURE_TYPE_4A = "4A"
TEXTURE_TYPE_4B = "4B"
TEXTURE_TYPE_4C = "4C"

# feature -others
STRING_SHORT = "Short"
STRING_MEDIUM = "Medium"
STRING_LONG = "Long"
STRING_LOW = "Low"
STRING_HIGH = "High"
STRING_NONE = "None"
STRING_PERM_OR_RELAXER = "Perm/Relaxer"
STRING_DYED = "Dyed"
STRING_BLEACHED = "Bleached"

# feature - texture number
TEXTURE_TYPE_1A_1B_NUMBER = 1
TEXTURE_TYPE_1C_NUMBER = 2
TEXTURE_TYPE_2A_NUMBER = 3
TEXTURE_TYPE_2B_NUMBER = 4
TEXTURE_TYPE_2C_NUMBER = 5
TEXTURE_TYPE_3A_NUMBER = 6
TEXTURE_TYPE_3B_NUMBER = 7
TEXTURE_TYPE_3C_NUMBER = 8
TEXTURE_TYPE_4A_NUMBER = 9
TEXTURE_TYPE_4B_NUMBER = 10
TEXTURE_TYPE_4C_NUMBER = 11

# feature - other number
STRING_SHORT_NUMBER = 1
STRING_MEDIUM_NUMBER = 2
STRING_LONG_NUMBER = 3
STRING_LOW_NUMBER = 1
STRING_HIGH_NUMBER = 3
STRING_NONE_NUMBER = -1
STRING_PERM_OR_RELAXER_NUMBER = 1
STRING_DYED_NUMBER = 2
STRING_BLEACHED_NUMBER = 3

# feature key in sheet
KEY_HAIR_TYPE = "Hair Type"
KEY_TEXTURE = "Texture"
KEY_LENGTH = "Length"
KEY_DENSITY = "Density"
KEY_POROSITY = "Porosity"
KEY_PROCESSING = "Processing"

# helper
STRING_HELPER = "Helper Table"
